import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}
      >
        <header className="bg-slate-800  p-4 flex justify-between items-center text-2xl text-white">
          <Link href="/">This is a site about code smell</Link>
          <nav className="flex gap-2">
            <Link href="/SpagettiOne"> one</Link>
            <Link href="/SpagettiTwo"> two</Link>
            <Link href="/SpagettiThree"> three</Link>
            <Link href="/SpagettiFour"> four</Link>
          </nav>
        </header>

        <div className="content" style={{ flex: "1" }}>
          {children}
        </div>

        <footer className="bg-slate-800 flex justify-center items-end p-4">
          <p className="text-white">Footer</p>
        </footer>
      </body>
    </html>
  );
}
